// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 

class DefaultFirebaseOptions {
  
  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqTpYlmf37vJxVJmVi8XUIZBlX5SGiOW8',
    appId: '1:321253638705:web:0d19daf4e4bf594cd20b10',
    messagingSenderId: '321253638705',
    projectId: 'login-85b36',
    authDomain: 'login-85b36.firebaseapp.com',
    storageBucket: 'login-85b36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0ZHlj1ukxY90zCB8U-MHdlfA5CzJ1aIk',
    appId: '1:321253638705:android:49c7940c2aa62bbcd20b10',
    messagingSenderId: '321253638705',
    projectId: 'login-85b36',
    storageBucket: 'login-85b36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3TBctPZ8Ba0Jhj5OHNIksRmgXE_Gkqko',
    appId: '1:321253638705:ios:43d0ab50a7a81ce4d20b10',
    messagingSenderId: '321253638705',
    projectId: 'login-85b36',
    storageBucket: 'login-85b36.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3TBctPZ8Ba0Jhj5OHNIksRmgXE_Gkqko',
    appId: '1:321253638705:ios:ff38c79b54dd4c3ad20b10',
    messagingSenderId: '321253638705',
    projectId: 'login-85b36',
    storageBucket: 'login-85b36.appspot.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
